### ISSUE TITLE
Having An Issue With The System

### ISSUE THREAD

**Issue by BasonTaylor** [n00bmobile/Bank-Robbery-System#1]
What do i put in the can rob and cant rob section there TEAM_ or There Command This is what i did i Put the Teams and it says canot rob as thief
and sutch please help

**Comment by n00bmobile** [comment]
You should try reading the description. TEAM_ or Team Commands aren't used! You need to put the exact same name in-game. EX: If you want to add the TEAM_THIEF then you add his name to the team table, like Thief. Please be aware that this is case sensitive.
Read the description before downloading or asking for help with an addon!!!

**Comment by BasonTaylor** [comment]
i have put the team names in not the TEAM_ NAmes it still is saying the
same thing i did read the readme thing and did what it asked and still not
working :/
i put the exact names

**Comment by n00bmobile** [comment]
Please add me on steam so we can continue this conversation.
