### ISSUE TITLE
Too many netmessages going server->client

### ISSUE THREAD

**Issue by Exho1** [n00bmobile/Bank-Robbery-System#4]
I ran a little net message tracker on a server and discovered that your bank robbery system seems to send 2 strings to the client every tick. This seems kinda silly and inefficient from an outside perspective but maybe you have your reasons. Regardless I believe that it would be beneficial if you just sent the time at the start of an event and let the client calculate it or send it every 5 seconds or so the client stays updated. Really anything beyond sending tons of net messages to the client per second would be great

Edit: I looked into your source code and found the solution to the problem. You are updating the client in a think hook so every tick they get an update about the time but 99% of the netmessages are the exact same thing which is just wasteful. 

https://github.com/n00bmobile/Bank-Robbery-System/blob/master/lua/entities/bankrobbery/init.lua#L388

Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:15
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault
Reading string  Robbing: 02:14
Reading string  Bank Vault

**Comment by DammitStella** [comment]
An bloody timer instead of the think hook is an good quick solution. Otherwise networked vars would be the way to go. but im too lazy to change that.

**Comment by bmwalters** [comment]
tomelyr please

**Comment by DammitStella** [comment]
its 5am here. This Thing even uses global vars. I need some serious sleep.

**Comment by n00bmobile** [comment]
Sorry for taking too long to askwer. The code is being redone since it uses a lot of things that I don't use anymore. I'm always learning things so It's time to remake it right. I'm not going to make the client calculate anything since there's a lot of things that can unsync the clients with the server timer. The remake will only send messages after being loaded/reloaded and 1 second messages during timers.

P.S: The Global Vars are needed, just take a closer look at how the Bank works and you'll see that multiple Banks working separately aren't going to work. (I THINK YOU MEAN THAT IS BETTER TO USE SELF VARS... OR MAYBE IT'S ANOTHER THING BUT FAK IT)
TIP: 3 Banks with the siren sound at the same time... Nightmare.

**Comment by n00bmobile** [comment]
Issue Fixed... It's too late to post something now. I'll be updating it tomorrow. Thanks for the report!

**Comment by Exho1** [comment]
Alright awesome! And also you could have the client calculate it but update it from the server every 5 seconds or so. Really anything to reduce the load on the client

**Comment by n00bmobile** [comment]
I'll test and see if doing this works well. If I don't add it, then you'll know why... :/

**Comment by n00bmobile** [comment]
I just tested... Doesn't work very well. Minimazing the game or doing other kinds of stuff usyncs the client. Anyway, It's fixed now and you can try to run this test again on the newer version. I'm closing this report, if you want, you can reach me on Steam. (Same name)
