### ISSUE TITLE
Not appearing 

### ISSUE THREAD

**Issue by npd1124** [n00bmobile/Bank-Robbery-System#6]
I am having an issue with the script, A data file is not being created as to the position of the bank even when I save it through console. It says in chat that the bank was saved but when I restart the server itis not there. I looked in the data folder and i saw a folder in there named bankrs but there is no file inside of it.

**Comment by n00bmobile** [comment]
This issue seems to be happening only to you. Can you inform me the name of tha map and the list of your current addons?

**Comment by n00bmobile** [comment]
Due to the absence of an askwer, I'll consider this issue as closed.

**Comment by npd1124** [comment]
Sorry I didnt see the email, I am trying and am getting this error in console 

 Lua Error: [ERROR] addons/bankrobbery/lua/entities/bank_vault/init.lua:193: attempt to call global 'permaSpawnLoad' (a nil value) 1. unknown - addons/bankrobbery/lua/entities/bank_vault/init.lua:193 2. unknown - lua/includes/modules/concommand.lua:54

**Comment by npd1124** [comment]
it seems like this guy has the issue too http://gyazo.com/a0e5493cc892f745d7c99082dc792658

**Comment by npd1124** [comment]
I updated to the latest version and I dont get any message say it was saved just that error in console

**Comment by n00bmobile** [comment]
Please, provide me the LUA ERROR.

**Comment by n00bmobile** [comment]
Are you sure?
Try disabling "host_workshop_collection", if you have it. Also, remove the Bank's .GMA file downloaded by it. After that, redownload the github version and try again without changing anything, not even the config. If it works, then you can start editing it, if not, inform me.

**Comment by npd1124** [comment]
How do I go about doing that

**Comment by n00bmobile** [comment]
I can't really teach you the basics of making a server, try finding tutorials. If this doesn't help, call me.

**Comment by npd1124** [comment]
I am not by any means a noob, I have been running servers for over 2 years.  I downloaded it from github and installed it that way from the very beginning.

**Comment by n00bmobile** [comment]
Redownload the newest version from github, it has been updated. Also, how can you run servers for over 2 years and not know that "host_workshop_collection" even existed?

**Comment by npd1124** [comment]
I have never heard it in that context before
