### ISSUE TITLE
Just question about BankConfig.TeamRequired

### ISSUE THREAD

**Issue by AMD-NICK** [n00bmobile/Bank-Robbery-System#9]
Hi. Why do you use name of teams like "Thief" instead the TEAM_THIEF as example?

**Comment by n00bmobile** [comment]
I don't really know, using string name seems easier to me than TEAM_ENUMS for some reason. I don't really see a reason for complaining about it.

**Comment by AMD-NICK** [comment]
Some peoples like to change his job names. DarkRP.createJob("Medic"... DarkRP.createJob("Doctor"

**Comment by n00bmobile** [comment]
Well, cool... What about changing the name on the config as well? I mean, you can change TEAM_ENUMS too.
Anyway, useless conversation with no point for such a small thing with little to no impact.
It's easy to change as well.

**Comment by n00bmobile** [comment]
I'll be closing this now, It's not something I'm planning to change.
Thanks for your time anyway!
I'm still "testing" the merge request, time isn't being friendly to me recently.
